### ISSUE TITLE
Question: list files modified/added in archive

### ISSUE THREAD

**Issue by saptarshiguha** [jborg/attic#301] opened 2015-04-30 21:43 UTC
Hello,

Lovely software.Thanks. 

Once I've added an archive

attic create --stats archivename

is there a way to show files added/modified (essentially a diff between this and the previous archive in time)

Cheers

**Comment by ThomasWaldmann** [comment] 2015-05-02 22:24
alternatively, with a better create -v output, one could get that list from there also.

**Comment by ThomasWaldmann** [comment] 2015-05-17 23:17
Duplicate of #158, please close.

**Closed** 2015-05-18 02:42 UTC
